import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import Providers from './providers';


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ 
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Providers>
        <nav className = "flex items-center justify-between bg-gray-100 px-6 py-3 border-b">
          <div className = "text-xl font-bold">Kanban Board</div>
          <div className = "flex gap-4 text-sm">
            <Link href = "/" className = "hover:underline">Home</Link>
            <Link href = "/about" className = "hover:underline">About</Link>
            <Link href="/login" className="hover:underline">Login</Link>
            <Link href = "/boards" className = "hover:underline">Boards</Link>
          </div>
        </nav>
        {children}
        </Providers>
      </body>
    </html>
  );
}


